# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
language: python
matrix:
  include:
  - env: CACHE_NAME=8.0 DEPLOY_DOC_FROM_BRANCH=master DEPLOY_DOC_TO_DIRECTORY=/ SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-9.0-Ubuntu_18.04-x86_64.tar.bz2
    dist: trusty
install:
- ./.travis-install.sh
script:
- ./.travis-test.sh
cache:
  directories:
  - $HOME/SageMath
  - $HOME/.cache/matplotlib
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
# after_success:
# - ./.travis-deploy-doc.sh
# before_script:
# - openssl aes-256-cbc -K $encrypted_f96cc3b3888c_key -iv $encrypted_f96cc3b3888c_iv
#  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d || true

addons:
  apt:
    packages:
     # On 8.0 with trusty, Fortran compiler is needed.
     # Otherwise, numpy cannot be imported.
     # Also, optional package installs in .travis-install.sh will trigger build of sage gcc.
     - gfortran
