language: python
services:
- docker
before_install:
- docker pull sagemath/sagemath:latest
script:
- docker run -v `pwd`:/multipolynomial-bases sagemath/sagemath:9.0 bash /multipolynomial-bases/build_and_test_in_sage.bash
before_script:
- openssl aes-256-cbc -K $encrypted_e052a2579e65_key -iv $encrypted_e052a2579e65_iv
  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: bash -x .travis-deploy-doc.sh
#    on:
#      branch: master
#      condition: -r .travis_ci_gh_pages_deploy_key
