
language: python

services:
  - docker

before_install:
  - docker pull sagemath/sagemath:latest

script:
  - docker run -v `pwd`:/multipolynomial-bases sagemath/sagemath:9.0 bash /multipolynomial-bases/build_and_test_in_sage.bash
